### ISSUE TITLE
Warning due to extra line

### ISSUE THREAD

**Issue by russelhowe** [leanbit/ansible-netdata#2]
When running this role as retrieved from ansible galaxy, I get this warning:
```
 [WARNING]: While constructing a mapping from
/home/user/ansible/roles/leanbit.netdata/tasks/main.yml, line 23, column 7, found a duplicate dict key (dest). Using last defined value only.
```

Looks to me like lines 24 and 26 of `tasks/main.yml` are in conflict, I think line 24 can be safely deleted.

**Comment by michelemina** [comment]
Thanks for the tip
